### ISSUE TITLE
DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by ringo360** [ringo360/Discord.js_Bot#19]
コマンドの登録に失敗する。
```
DiscordAPIError[50035]: Invalid Form Body
22[APPLICATION_COMMANDS_DUPLICATE_NAME]: Application command names must be unique
    at handleErrors (/home/svr2-360/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/svr2-360/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:1072:23)
    at async SequentialHandler.queueRequest (/home/svr2-360/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:913:14)
    at async _REST.request (/home/svr2-360/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async ApplicationCommandManager.set (/home/svr2-360/Sekai.Explode/node_modules/discord.js/src/managers/ApplicationCommandManager.js:171:18)
    at async Client.<anonymous> (/home/svr2-360/Sekai.Explode/discordbot.js:133:2) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ]
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { '22': [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v10/applications/1144600133762293800/commands'
}
```

**Comment by ringo360** [comment]
@takejohn can u help me?

**Comment by ringo360** [comment]
fixed in [last commit](https://github.com/TeamSekai/Sekai.Explode/commit/793f4f96f9ef2dfe71797f76b52ee68b01c6c17f)
