### ISSUE TITLE
/follow_annoucementsでUnknown interactionエラーが出る

### ISSUE THREAD

**Issue by ringo360** [ringo360/Discord.js_Bot#45]
**バグについての説明**
`/follow_announcements`の実行時に以下のエラーが発生する
```
DiscordAPIError[10062]: Unknown interaction
    at handleErrors (/home/ringoxd/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BurstHandler.runRequest (/home/ringoxd/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:786:23)
    at async _REST.request (/home/ringoxd/Sekai.Explode/node_modules/@discordjs/rest/dist/index.js:1218:22)
    at async ChatInputCommandInteraction.reply (/home/ringoxd/Sekai.Explode/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:111:5)
    at async Client.<anonymous> (/home/ringoxd/Sekai.Explode/discordbot.js:142:4) {
  requestBody: { files: [], json: { type: 4, data: [Object] } },
  rawError: { message: 'Unknown interaction', code: 10062 },
  code: 10062,
  status: 404,
  method: 'POST',
  url: 'https://discord.com/api/v10/interactions/1212694122264137768/xxxxxxx/callback'
}
[Sekai.Explode] new follower! xxxxxx - xxxxxx
```

**再現方法**
1. Sekai.Explodeを稼働・追加
2. 適当なチャンネルに対して`/follow_announcements`を実行
3. サーバーログにエラーが表示

**期待される振る舞い(動作)**
エラーが発生せずに`[Sekai.Explode] new follower! (ギルド名) - (ギルドID)`が表示される

**スクリーンショット**
ねえよ

**動作環境(この項目を埋めてください。):**
 - OS: Ubuntu20.04
 - Node.jsのバージョン: v18.17.1
**補足説明**
なんでなんでなんでなんでなんでなんでなんでなんでなんでなんで

**Comment by takejohn** [comment]
多分ここ `editReply` を `await` してないから…
https://github.com/TeamSekai/Sekai.Explode/blob/361610433937053d62ba60fd9dd524bb9cb7df17/commands/receiveupdate.js#L22-L30

**Comment by ringo360** [comment]
そこawaitしようとしたら怒られた

**Comment by ringo360** [comment]
closed in #49 , ty!
