### ISSUE TITLE
テストが終わった後に MongoDB に接続しようとする

### ISSUE THREAD

**Issue by takejohn** [ringo360/Discord.js_Bot#60]
**バグについての説明**
Jestでテストを実行すると次のような警告が出る。
`internal/messages.js` を実行することで、`internal/mongoodb.js` がインポートされ、
テストが終わった後に MongoDB に接続するコードが実行される。
```ansi
  ●  Cannot log after tests are done. Did you forget to wait for something async in your test?
    Attempted to log "[MongoDB] 接続しました！".

      21 | });
      22 | db.on('connected', function () {
    > 23 |      console.log(LANG.internal.mongodb.dbConnected);
         |              ^
      24 | });
      25 | db.on('disconnecting', function () {
      26 |      console.log(LANG.internal.mongodb.dbDisconnecting);

      at console.log (node_modules/@jest/console/build/BufferedConsole.js:156:10)
      at NativeConnection.log (internal/mongodb.js:23:10)
      at NativeConnection.set (node_modules/mongoose/lib/connection.js:123:12)
      at NativeConnection.Object.<anonymous>.Connection.onOpen (node_modules/mongoose/lib/connection.js:732:19)
      at _setClient (node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:400:8)
      at NativeConnection.createClient (node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:303:3)
      at NativeConnection.openUri (node_modules/mongoose/lib/connection.js:824:5)
      at connectMongoose (internal/mongodb.js:10:3)
```

**再現方法**
1. プロジェクトルートで Jest を実行
    ```sh
    jest
    ```

**期待される振る舞い(動作)**
テストのときは MongoDB に接続しようとしない。

**スクリーンショット**
なし

**動作環境(この項目を埋めてください。):**
 - OS: Ubuntu 22.04.4
 - Node.jsのバージョン: v21.6.2
 - Jest のバージョン: 29.7.0

**補足説明**
後で自分で対処する。

**Comment by ringo360** [comment]
yay! fixed in #61
